### ISSUE TITLE
About persistent session

### ISSUE THREAD

**Issue by vtellez** [Pitchanon/Laravel4-FacebookConnect#2]
Hello, I use this great package to connect my app with facebook. 

When users connects their account, they can post on facebook through my app, but after a while the session is disconnected and no longer can keep publishing. 

Is there any way to define persistent session?

**Comment by Pitchanon** [comment]
Let me check, I will feedback you shortly.

Thank.

**Comment by vtellez** [comment]
Hi Pitchanon, 

I solved the problem using the app token instead of the user token that does not expire. 

For now I solved the problem by directly calling the web service facebook like this:

exec("curl -X POST -F 'name=".$name."' -F 'description=".$desc."' -F 'message=".$msg."' -F 'access_token=APP_ACCESS_TOKEN' https://graph.facebook.com/".$facebook_id."/feed -F 'link=".$link."' -F 'picture=".$picture."'");
