### ISSUE TITLE
Illegal string offset 'permission'

### ISSUE THREAD

**Issue by vtellez** [Pitchanon/Laravel4-FacebookConnect#5]
Hi, 

when I define my app's permission like this:

$permissions = 'email, publish_stream, publish_actions';

I've received the following php error: Illegal string offset 'permission' in this code:

```
    // check if the permissions we need have been allowed by the user
    // if not then redirect them again to facebook's permissions page
    foreach ($permissions_array as $perm) {
        $perm_unlisted = false;
        foreach($permissions_list['data'][0] as $fb_perm)
        {
            if($fb_perm['permission'] == $perm && $fb_perm['status'] == 'granted')
            {
                $perm_unlisted = true;
```

Its seems to be produced by php 5.4 (http://stackoverflow.com/questions/15361392/how-do-i-correct-this-illegal-string-offset)

But I am not sure how can i fixed it.

Can you help me? Thanks

Regards,

**Comment by brndwgn** [comment]
Hi,

Line 147 in Pitchanon/FacebookConnect/Provider/Connect.php need to be:

```
if(is_array($fb_perm) && $fb_perm['permission'] == $perm && $fb_perm['status'] == 'granted')
```

as the variable '$fb_perm' is sometimes a string not an array.

Regards
